name: 'Git Secret Reveal Action'
description: 'Reveal the secrets committed into your repo'
branding:
  icon: unlock
  color: green
inputs:
  gpg-private-key:
    description: 'The GPG private key to use, you can export this using the command: gpg --armour --export-secret-keys KEY_ID'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gpg-private-key }}
