on: [ push ]

jobs:
  git_secret_job:
    runs-on: ubuntu-latest
    name: A job to reveal secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Secret Reveal Step
        id: git-secret
        uses: ./
        with:
          gpg-secret-key: ${{ secrets.GPG_PRIVATE_KEY }}
