on: [ push ]

jobs:
  git_secret_job:
    runs-on: ubuntu-latest
    name: Reveal Secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Secret Reveal Step
        id: git-secret
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Assert the secret Exists
        run: |
          SECRET=$(cat .env | grep "ACTION")
          if [ "$SECRET" = "ACTION=git-secret-action-WRONG" ]
          then
            exit 0
          else
            exit 1
          fi
